title: "Geoff Pritchard"
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Learning from scratch. Starting my Act II as an On Deck No-Code Fellow
baseurl: "/" 
url: "/gpritchard" 
twitter_username: GeoffPritchard
github_username:  

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg